name: Android CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
      allowfailure:
        required: false
        type: boolean
        default: false

jobs:
  buildGradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: |
        chmod +x gradlew
        ./gradlew build
      if: inputs.compiler == 'gradle'

    - name: Run Tests with Gradle
      run: |
        chmod +x gradlew
        ./gradlew test
      if: inputs.compiler == 'gradle' && success()

    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      if: success()
      with:
        name: "${{ github.sha }}"
        path: app/build
