name: Android CI

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      build_image:
        required: true
        type: string
      compiler:
        required: true
        type: string

jobs:
  buildGradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.3.0
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - run: |
           chmod +x gradlew
           ./gradlew build
           echo "End CI"
    - uses: actions/upload-artifact@v3.1.1
      if: success()
      with:
        name: "${{ github.sha }}"
        
