name: PMD Code Analysis

on:
  push:
    branches-ignore:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  pmd-code-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run PMD Code Analysis
        uses: pmd/pmd-github-action@v1
        with:
          rulesets: 'kotlin-basic,kotlin-errorprone'
          sourcePath: 'src/main/kotlin'
          analyzeModifiedFilesOnly: false

      - name: Upload PMD Report
        uses: actions/upload-artifact@v2
        with:
          name: pmd-report
          path: pmd-report
