name: Terracode/Sonarcloud

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      compiler:
        required: true
        type: string
      allowfailure:
        required: false
        type: boolean
        default: false

jobs:
  sonarcloud-check:
    runs-on: ubuntu-latest
    env:
          SONAR_TOKEN: "${{ secrets.SONAR_TOKEN }}"
          SONAR_HOST_URL: "${{ vars.SONAR_HOST_URL}}"
          GIT_DEPTH: 0
    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
    - uses: actions/download-artifact@v3.0.1
      if: ${{ inouts.compiler == 'gradle'}}
      with:
        name: "${{ github.sha }}"
        path: build
    - uses: actions/download-artifact@v3.0.1
      if: ${{ inputs.compiler == 'maven'}}
      with:
        name: "${{ github.sha }}"
        path: main/target
