name: caller workflow

on: 
  push:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  call-workflow-buildgradle:
    uses: Capstone-Terracoders/Mobile-Application/.github/workflows/android.yml@main  # Update with the correct branch and path
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit

  call-workflow-sonarcloud:
    needs: call-workflow-buildgradle
    uses: Capstone-Terracoders/Mobile-Application/.github/workflows/sonarcloud.yml@main  # Update with the correct branch and path
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit
