name: caller workflow

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  call-workflow-android:
    uses: ./.github/workflows/android.yml
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit

  call-workflow-pmd:
      uses: ./.github/workflows/pmd.yml
      with:
        compiler: gradle
        allowfailure: false
      secrets: inherit
