name: caller workflow

on: 
  push:
  workflow_dispatch:

jobs:
  call-workflow-buildgradle:
    uses: ./android.yml  # Update with the correct file name
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit

  call-workflow-sonarcloud:
    needs: call-workflow-buildgradle
    uses: ./sonarcloud.yml  # Update with the correct file name
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit
