name: caller workflow

on: 
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  call-workflow-android:
    uses: ./.github/workflows/android.yml  # Update with the correct file path
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit

  call-workflow-sonarcloud:
    needs: call-workflow-android
    uses: ./.github/workflows/sonarcloud.yml  # Update with the correct file path
    with:
      compiler: gradle
      allowfailure: false
    secrets: inherit
